exports.optionSeed = [
  {
    optionId:1,
    name:'Hospital',
    inputType:'dropdown',
    callFieldName:'hospital',
    options:[
      {
        id:1,
        name:'Erlanger Main'
      },
      {
        id:2,
        name:'Erlanger East'
      },
      {
        id:3,
        name:'Erlanger North'
      },
      {
        id:4,
        name:"Erlanger Children's"
      },
      {
        id:5,
        name:"Erlanger Bledsoe"
      },
      {
        id:6,
        name:"Siskin"
      }
    ]
  },
  {
    optionId:2,
    name:'Medical Record Number',
    inputType:'number',
    callFieldName:'mrn'
  },
  {
    optionId:3,
    name:'Provider',
    inputType:'text',
    callFieldName:'provider'
  },
  {
    optionId:4,
    name:'MD Order Changed?',
    inputType:'confirm',
    callFieldName:'orderChange',
    options:[
      {
        id:1,
        name:'PICC changed to ML'
      },
      {
        id:2,
        name:'PICC changed to IV'
      },
      {
        id:3,
        name:'ML changed to IV'
      },
      {
        id:4,
        name:'ML changed to PICC'
      },
      {
        id:5,
        name:'IV changed to PICC'
      },
      {
        id:6,
        name:'IV changed to ML'
      }
    ]
  },
  {
    optionId:5,
    name:'Consultation',
    inputType:'checkbox',
    callFieldName:'wasConsultation'
  },
  {
    optionId:6,
    name:'Call Needs',
    inputType:'dropdown',
    callFieldName:'callNeeds',
    options:[
      {
        id:1,
        name:'New IV'
      },
      {
        id:2,
        name:'Lab Draw'
      },
      {
        id:3,
        name:'Labs + IV'
      },
      {
        id:4,
        name:'Blood Culture'
      },
      {
        id:5,
        name:'PICC Line'
      },
      {
        id:6,
        name:'ML'
      },
      {
        id:7,
        name:'Port Access'
      },
      {
        id:8,
        name:'Port De-Access'
      },
      {
        id:9,
        name:'Troubleshoot'
      },
      {
        id:10,
        name:'Dressing Change'
      },
      {
        id:11,
        name:'Custom'
      }
    ]
  },
  {
    optionId:7,
    name:'Status Codes',
    inputType:'dropdown',
    callFieldName:'status',
    options:[
      {
        id:1,
        name:'Normal'
      },
      {
        id:2,
        name:'Stat'
      },
      {
        id:3,
        name:'On Hold'
      }
    ]
  }
];

exports.referencesObject = {
  procedures:{
    '1':{
      seq:1,
      name:'PIV'
    },
    '2':{
      seq:2,
      name:'Lab Draw'
    },
    '3':{
      seq:3,
      name:'Blood Culture'
    },
    '4':{
      seq:4,
      name:'Port-A-Cath'
    },
    '5':{
      seq:5,
      name:'PICC Line'
    },
    '6':{
      seq:6,
      name:'Dressing Change'
    },
    '7':{
      seq:7,
      name:'Troubleshoot'
    },
    '8':{
      seq:8,
      name:'Insertion Procedure'
    }
  },
  groups:{
    '1':{
      seq:1,
      name:'Patient Refused'
    },
    '2':{
      seq:2,
      name:'Size'
    },
    '3':{
      seq:3,
      name:'Care Type'
    },
    '4':{
      seq:4,
      name:'DC IV'
    },
    '5':{
      seq:5,
      name:'Ultrasound'
    },
    '6':{
      seq:6,
      name:'Blood Drawn'
    },
    '7':{
      seq:7,
      name:'Draw Type'
    },
    '8':{
      seq:8,
      name:'From'
    },
    '9':{
      seq:9,
      name:'Type'
    },
    '10':{
      seq:10,
      name:'Removal'
    },
    '11':{
      seq:11,
      name:'What'
    },
    '12':{
      seq:12,
      name:'Why'
    },
    '13':{
      seq:13,
      name:'Intervention'
    },
    '14':{
      seq:14,
      name:'Cathflow'
    },
    '15':{
      seq:15,
      name:'Insertion Type'
    },
    '16':{
      seq:16,
      name:'Vessel'
    },
    '17':{
      seq:17,
      name:'Laterality'
    },
    '18':{
      seq:18,
      name:'Insertion Length'
    },
    '19':{
      seq:19,
      name:'Hospital Staff Obtained'
    }
  }
};


exports.itemSeed = [
  {
    itemId:1,
    procedureId:1,
    groupId:1,
    value:'Patient Refused',
    isCustom:false
  },
  {
    itemId:2,
    procedureId:1,
    groupId:2,
    value:'24g',
    isCustom:false
  },
  {
    itemId:3,
    procedureId:1,
    groupId:2,
    value:'22g',
    isCustom:false
  },
  {
    itemId:4,
    procedureId:1,
    groupId:2,
    value:'20g',
    isCustom:false
  },
  {
    itemId:5,
    procedureId:1,
    groupId:2,
    value:'18g',
    isCustom:false
  },
  {
    itemId:6,
    procedureId:1,
    groupId:3,
    value:'IV Flushed',
    isCustom:false
  },
  {
    itemId:7,
    procedureId:1,
    groupId:3,
    value:'Saline Locked',
    isCustom:false
  },
  {
    itemId:8,
    procedureId:1,
    groupId:3,
    value:'Dressing Changed',
    isCustom:false
  },
  {
    itemId:9,
    procedureId:1,
    groupId:3,
    value:'Dressing Reinforced',
    isCustom:false
  },
  {
    itemId:10,
    procedureId:1,
    groupId:4,
    value:'Inflitration',
    isCustom:false
  },
  {
    itemId:11,
    procedureId:1,
    groupId:4,
    value:'Phlebitis',
    isCustom:false
  },
  {
    itemId:12,
    procedureId:1,
    groupId:4,
    value:'PT Removal',
    isCustom:false
  },
  {
    itemId:13,
    procedureId:1,
    groupId:4,
    value:'Leaking',
    isCustom:false
  },
  {
    itemId:14,
    procedureId:1,
    groupId:4,
    value:'Painful',
    isCustom:false
  },
  {
    itemId:15,
    procedureId:1,
    groupId:4,
    value:'Per Protocol',
    isCustom:false
  },
  {
    itemId:16,
    procedureId:1,
    groupId:5,
    value:'US Used',
    isCustom:false
  },
  {
    itemId:17,
    procedureId:1,
    groupId:6,
    value:'Blood Was Drawn',
    isCustom:false
  },
  {
    itemId:71,
    procedureId:1,
    groupId:19,
    value:'Hospital Staff Obtained',
    isCustom:false
  },
  {
    itemId:18,
    procedureId:2,
    groupId:1,
    value:'Patient Refused',
    isCustom:false
  },
  {
    itemId:19,
    procedureId:2,
    groupId:7,
    value:'From IV',
    isCustom:false
  },
  {
    itemId:20,
    procedureId:2,
    groupId:7,
    value:'Labs Only',
    isCustom:false
  },
  {
    itemId:21,
    procedureId:2,
    groupId:5,
    value:'US Used',
    isCustom:false
  },
  {
    itemId:72,
    procedureId:1,
    groupId:19,
    value:'Hospital Staff Obtained',
    isCustom:false
  },
  {
    itemId:22,
    procedureId:3,
    groupId:1,
    value:'Patient Refused',
    isCustom:false
  },
  {
    itemId:23,
    procedureId:3,
    groupId:8,
    value:'PICC',
    isCustom:false
  },
  {
    itemId:24,
    procedureId:3,
    groupId:8,
    value:'ML',
    isCustom:false
  },
  {
    itemId:25,
    procedureId:3,
    groupId:8,
    value:'Central Line',
    isCustom:false
  },
  {
    itemId:26,
    procedureId:3,
    groupId:8,
    value:'IV',
    isCustom:false
  },
  {
    itemId:27,
    procedureId:3,
    groupId:8,
    value:'Peripheral Stick x 1',
    isCustom:false
  },
  {
    itemId:28,
    procedureId:3,
    groupId:8,
    value:'Peripheral Stick x 2',
    isCustom:false
  },
  {
    itemId:29,
    procedureId:3,
    groupId:5,
    value:'US Used',
    isCustom:false
  },
  {
    itemId:30,
    procedureId:4,
    groupId:9,
    value:'Access',
    isCustom:false
  },
  {
    itemId:31,
    procedureId:4,
    groupId:9,
    value:'De-Access',
    isCustom:false
  },
  {
    itemId:32,
    procedureId:5,
    groupId:10,
    value:'Therapy Complete',
    isCustom:false
  },
  {
    itemId:33,
    procedureId:5,
    groupId:10,
    value:'Discharge',
    isCustom:false
  },
  {
    itemId:34,
    procedureId:5,
    groupId:10,
    value:'Clotted',
    isCustom:false
  },
  {
    itemId:35,
    procedureId:5,
    groupId:10,
    value:'Contaminated',
    isCustom:false
  },
  {
    itemId:36,
    procedureId:5,
    groupId:10,
    value:'PT Removal',
    isCustom:false
  },
  {
    itemId:37,
    procedureId:6,
    groupId:11,
    value:'PICC',
    isCustom:false
  },
  {
    itemId:38,
    procedureId:6,
    groupId:11,
    value:'Port-A-Cath',
    isCustom:false
  },
  {
    itemId:39,
    procedureId:6,
    groupId:11,
    value:'Central Line',
    isCustom:false
  },
  {
    itemId:40,
    procedureId:6,
    groupId:11,
    value:'ML',
    isCustom:false
  },
  {
    itemId:41,
    procedureId:6,
    groupId:12,
    value:'Per Protocol',
    isCustom:false
  },
  {
    itemId:42,
    procedureId:6,
    groupId:12,
    value:'Bleeding',
    isCustom:false
  },
  {
    itemId:43,
    procedureId:6,
    groupId:12,
    value:'Site Assessment',
    isCustom:false
  },
  {
    itemId:44,
    procedureId:6,
    groupId:12,
    value:'Dressing Compromised',
    isCustom:false
  },
  {
    itemId:45,
    procedureId:7,
    groupId:11,
    value:'ML',
    isCustom:false
  },
  {
    itemId:46,
    procedureId:7,
    groupId:11,
    value:'PICC',
    isCustom:false
  },
  {
    itemId:47,
    procedureId:7,
    groupId:11,
    value:'Central Line',
    isCustom:false
  },
  {
    itemId:48,
    procedureId:7,
    groupId:11,
    value:'Port',
    isCustom:false
  },
  {
    itemId:49,
    procedureId:7,
    groupId:11,
    value:'IV',
    isCustom:false
  },
  {
    itemId:50,
    procedureId:7,
    groupId:13,
    value:'Power Flush',
    isCustom:false
  },
  {
    itemId:51,
    procedureId:7,
    groupId:13,
    value:'Clave Change',
    isCustom:false
  },
  {
    itemId:52,
    procedureId:7,
    groupId:13,
    value:'Recommend DC',
    isCustom:false
  },
  {
    itemId:53,
    procedureId:7,
    groupId:13,
    value:'Line Retracted',
    isCustom:false
  },
  {
    itemId:54,
    procedureId:7,
    groupId:13,
    value:'Repositioned',
    isCustom:false
  },
  {
    itemId:55,
    procedureId:7,
    groupId:14,
    value:'PAC: Initiated',
    isCustom:false
  },
  {
    itemId:56,
    procedureId:7,
    groupId:14,
    value:'PAC: Completed',
    isCustom:false
  },
  {
    itemId:73,
    procedureId:7,
    groupId:14,
    value:'PICC: Initiated',
    isCustom:false
  },
  {
    itemId:74,
    procedureId:7,
    groupId:14,
    value:'PICC: Completed',
    isCustom:false
  },
  {
    itemId:75,
    procedureId:7,
    groupId:14,
    value:'CVL: Initiated',
    isCustom:false
  },
  {
    itemId:76,
    procedureId:7,
    groupId:14,
    value:'CVL: Completed',
    isCustom:false
  },
  {
    itemId:57,
    procedureId:8,
    groupId:1,
    value:'Patient Refused',
    isCustom:false
  },
  {
    itemId:58,
    procedureId:8,
    groupId:15,
    value:'SL PICC',
    isCustom:false
  },
  {
    itemId:59,
    procedureId:8,
    groupId:15,
    value:'DL PICC',
    isCustom:false
  },
  {
    itemId:60,
    procedureId:8,
    groupId:15,
    value:'TL PICC',
    isCustom:false
  },
  {
    itemId:61,
    procedureId:8,
    groupId:15,
    value:'ML',
    isCustom:false
  },
  {
    itemId:62,
    procedureId:8,
    groupId:15,
    value:'PG',
    isCustom:false
  },
  {
    itemId:63,
    procedureId:8,
    groupId:16,
    value:'Basilic',
    isCustom:false
  },
  {
    itemId:64,
    procedureId:8,
    groupId:16,
    value:'Brachial',
    isCustom:false
  },
  {
    itemId:65,
    procedureId:8,
    groupId:16,
    value:'Cephalic',
    isCustom:false
  },
  {
    itemId:66,
    procedureId:8,
    groupId:16,
    value:'Internal Jugular',
    isCustom:false
  },
  {
    itemId:67,
    procedureId:8,
    groupId:16,
    value:'Femoral',
    isCustom:false
  },
  {
    itemId:68,
    procedureId:8,
    groupId:17,
    value:'Left',
    isCustom:false
  },
  {
    itemId:69,
    procedureId:8,
    groupId:17,
    value:'Right',
    isCustom:false
  },
  {
    itemId:70,
    procedureId:8,
    groupId:18,
    value:'in CM',
    isCustom:true,
    fieldAbbr:'Len',
    valuePrefix:'',
    valueSuffix:'cm'
  }
];

exports.procedureSeed = [
  {
    procedureId:1,
    seq:1,
    groups:[
      {
        seq:1,
        groupId:1,
        inputType:'checkbox',
        hideHeader:true,
        groupItems:[1]
      },
      {
        seq:2,
        groupId:2,
        inputType:'radio',
        groupItems:[2,3,4,5]
      },
      {
        seq:3,
        groupId:5,
        inputType:'checkbox',
        groupItems:[16]
      },
      {
        seq:4,
        groupId:6,
        inputType:'checkbox',
        groupItems:[17]
      },
      {
        seq:5,
        groupId:3,
        inputType:'checkbox',
        groupItems:[6,7,8,9]
      },
      {
        seq:6,
        groupId:4,
        inputType:'checkbox',
        groupItems:[10,11,12,13,14,15],
      },
      {
        seq:7,
        groupId:19,
        inputType:'checkbox',
        groupItems:[71]
      }
    ]
  },
  {
    procedureId:2,
    seq:2,
    groups:[
      {
        seq:1,
        groupId:1,
        inputType:'checkbox',
        hideHeader:true,
        groupItems:[18]
      },
      {
        seq:2,
        groupId:7,
        inputType:'radio',
        groupItems:[19,20]
      },
      {
        seq:3,
        groupId:5,
        inputType:'checkbox',
        groupItems:[21]
      },
      {
        seq:4,
        groupId:19,
        inputType:'checkbox',
        groupItems:[72]
      }
    ]
  },
  {
    procedureId:3,
    seq:3,
    groups:[
      {
        seq:1,
        groupId:1,
        inputType:'checkbox',
        hideHeader:true,
        groupItems:[22]
      },
      {
        seq:2,
        groupId:8,
        inputType:'checkbox',
        groupItems:[23,24,25,26,27,28]
      },
      {
        seq:3,
        groupId:5,
        inputType:'checkbox',
        groupItems:[29]
      }
    ]
  },
  {
    procedureId:4,
    seq:4,
    groups:[
      {
        seq:1,
        groupId:9,
        hideHeader:true,
        inputType:'checkbox',
        groupItems:[30,31]
      }
    ]
  },
  {
    procedureId:5,
    seq:5,
    groups:[
      {
        seq:1,
        groupId:10,
        inputType:'radio',
        groupItems:[32,33,34,35,36]
      }
    ]
  },
  {
    procedureId:6,
    seq:6,
    groups:[
      {
        seq:1,
        groupId:11,
        inputType:'radio',
        groupItems:[37,38,39,40]
      },
      {
        seq:2,
        groupId:12,
        inputType:'radio',
        groupItems:[41,42,43,44]
      }
    ]
  },
  {
    procedureId:7,
    seq:7,
    groups:[
      {
        seq:1,
        groupId:11,
        inputType:'radio',
        groupItems:[45,46,47,48,49]
      },
      {
        seq:2,
        groupId:13,
        inputType:'checkbox',
        groupItems:[50,51,52,53,54]
      },
      {
        seq:3,
        groupId:14,
        inputType:'radio',
        hideHeader:true,
        groupItems:[55,56,73,74,75,76]
      }
    ]
  },
  {
    procedureId:8,
    seq:8,
    groups:[
      {
        seq:1,
        groupId:1,
        inputType:'checkbox',
        hideHeader:true,
        groupItems:[57]
      },
      {
        seq:2,
        groupId:15,
        inputType:'radio',
        groupItems:[58,59,60,61,62]
      },
      {
        seq:3,
        groupId:16,
        inputType:'radio',
        groupItems:[63,64,65,66,67]
      },
      {
        seq:4,
        groupId:17,
        inputType:'radio',
        groupItems:[68,69]
      },
      {
        seq:5,
        groupId:18,
        fieldName:'insertionLength',
        inputType:'number',
        groupItems:[70]
      }
    ]
  }
];